language: node_js
node_js:
  - "4"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/74fc4fea9c5debd4ad2e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
script:
  - npm run ci
before_install:
  - npm install -g istanbul mocha
